version: '3'
services:
  redis:
    image: redis

  django-channels:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver"
    ports: 
      - "8000:8000"
    depends_on:
      - redis